<?php 
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mário Sakamoto <mskamot@gmail.com>
	 * @see http://mariosakamoto.com/getz
	 */
	 
	namespace src\model; 

	class Medicoes {
			
		private $id;
		private $data_hora;
		private $altura_mar;
		private $humidade_ar;
		private $humidade_solo;
		private $pressao_ar;
		private $temperatura_ar;
		private $cadastrado;
		private $modificado;
			
		public function __construct() { }
			
		public function setId($id) {
			$this->id = $id;
		}
		
		public function getId() {
			return $this->id;
		}
					
		public function setData_hora($data_hora) {
			$this->data_hora = $data_hora;
		}
		
		public function getData_hora() {
			return $this->data_hora;
		}
					
		public function setAltura_mar($altura_mar) {
			$this->altura_mar = $altura_mar;
		}
		
		public function getAltura_mar() {
			return $this->altura_mar;
		}
					
		public function setHumidade_ar($humidade_ar) {
			$this->humidade_ar = $humidade_ar;
		}
		
		public function getHumidade_ar() {
			return $this->humidade_ar;
		}
					
		public function setHumidade_solo($humidade_solo) {
			$this->humidade_solo = $humidade_solo;
		}
		
		public function getHumidade_solo() {
			return $this->humidade_solo;
		}
					
		public function setPressao_ar($pressao_ar) {
			$this->pressao_ar = $pressao_ar;
		}
		
		public function getPressao_ar() {
			return $this->pressao_ar;
		}
					
		public function setTemperatura_ar($temperatura_ar) {
			$this->temperatura_ar = $temperatura_ar;
		}
		
		public function getTemperatura_ar() {
			return $this->temperatura_ar;
		}
					
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
		
		public function getCadastrado() {
			return $this->cadastrado;
		}
					
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
		
		public function getModificado() {
			return $this->modificado;
		}
					
	}
	
?>