<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mário Sakamoto <mskamot@gmail.com>
	 * @see http://mariosakamoto.com/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class Perfil_telasDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO perfil_telas (
				cadastrado
				, modificado
				, perfil
				, permissao
				, tela
				) VALUES";
				
		public $read = 
				"perfil_telas.id AS 'perfil_telas.id'
				, perfil_telas.cadastrado AS 'perfil_telas.cadastrado'
				, perfil_telas.modificado AS 'perfil_telas.modificado'
				, perfil_telas.perfil AS 'perfil_telas.perfil'
				, perfil_telas.permissao AS 'perfil_telas.permissao'
				, perfil_telas.tela AS 'perfil_telas.tela'
				";
				
		private $update = "UPDATE perfil_telas SET";
		private $delete = "DELETE FROM perfil_telas";
		
		public $from = "perfil_telas perfil_telas";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Perfil_telas}perfil_telas
		 */
		public function setCreate($perfil_telas) {		
			$this->sql = $this->create . " (\"" . 
					$perfil_telas->getCadastrado() .
					"\", \"" . $perfil_telas->getModificado() .
					"\", \"" . $perfil_telas->getPerfil() .
					"\", \"" . $perfil_telas->getPermissao() .
					"\", \"" . $perfil_telas->getTela() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$perfisDao = new model\PerfisDao($this->connection);
			$permissoesDao = new model\PermissoesDao($this->connection);
			$telasDao = new model\TelasDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $perfisDao->read . ", " . $permissoesDao->read . ", " . $telasDao->read . 
					" FROM " . $this->getFrom() .", " . $perfisDao->from . ", " . $permissoesDao->from . ", " . $telasDao->from . 
					($this->getWhere() == "" ? " WHERE perfil_telas.perfil = perfis.id AND perfil_telas.permissao = permissoes.id AND perfil_telas.tela = telas.id" : $this->getWhere()) . 
					" AND perfil_telas.perfil = perfis.id AND perfil_telas.permissao = permissoes.id AND perfil_telas.tela = telas.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Perfil_telas}perfil_telas  
		 * @param {String} where
		 */
		public function setUpdate($perfil_telas, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $perfil_telas->getId() . 
					"\", modificado = \"" . $perfil_telas->getModificado() . 
					"\", perfil = \"" . $perfil_telas->getPerfil() . 
					"\", permissao = \"" . $perfil_telas->getPermissao() . 
					"\", tela = \"" . $perfil_telas->getTela() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS 'perfil_telas.size' from perfil_telas" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "perfil_telas.size", $row["perfil_telas.size"]);
				
				$pages = ceil($row["perfil_telas.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "perfil_telas.pages", $pages);
				
				$pagination = "<select id=\"gz-select-pagination\" onchange=\"goPage();\">";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value=\"" . $i . "\" selected>" . $i . "</option>";
					else
						$pagination .= "<option value=\"" . $i . "\">" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "perfil_telas.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Perfil_telas} perfil_telas 
		 * @return {Boolean}
		 */
		public function create($perfil_telas) {
			$result = "";

			$this->setCreate($perfil_telas);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "perfil_telas.id", $row["perfil_telas.id"]);
				$this->setResponse($line, "perfil_telas.cadastrado", modelDateTime($row["perfil_telas.cadastrado"]));
				$this->setResponse($line, "perfil_telas.modificado", modelDateTime($row["perfil_telas.modificado"]));
				$this->setResponse($line, "perfil_telas.perfil", $row["perfil_telas.perfil"]);
				$this->setResponse($line, "perfis.perfil", $row["perfis.perfil"]);
				$this->setResponse($line, "perfil_telas.permissao", $row["perfil_telas.permissao"]);
				$this->setResponse($line, "permissoes.permissao", $row["permissoes.permissao"]);
				$this->setResponse($line, "perfil_telas.tela", $row["perfil_telas.tela"]);
				$this->setResponse($line, "telas.tela", $row["telas.tela"]);
			
				$this->setResponse($line, "perfil_telas.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Perfil_telas} perfil_telas 
		 * @return {Boolean}
		 */
		public function update($perfil_telas) {
			$result = "";
			
			$this->setUpdate($perfil_telas, "perfil_telas.id = " . $perfil_telas->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "perfil_telas.id", $row["perfil_telas.id"]);
				$this->setResponse($size, "perfil_telas.cadastrado", $row["perfil_telas.cadastrado"]);
			
				if ($row["perfil_telas.id"] == $selected)
					$this->setResponse($size, "perfil_telas.selected", "selected");
				else
					$this->setResponse($size, "perfil_telas.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "perfil_telas.id", $row["perfil_telas.id"]);
				$this->setResponse($size, "perfil_telas.cadastrado", $row["perfil_telas.cadastrado"]);
				$this->setResponse($size, "perfil_telas.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>