<?php 
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mário Sakamoto <mskamot@gmail.com>
	 * @see http://mariosakamoto.com/getz
	 */
	 
	namespace src\model; 

	class Temas {
			
		private $id;
		private $tema;
		private $identificador;
		private $cor_primaria;
		private $cor_secundaria;
		private $cor_texto;
		private $foto;
		private $cadastrado;
		private $modificado;
			
		public function __construct() { }
			
		public function setId($id) {
			$this->id = $id;
		}
		
		public function getId() {
			return $this->id;
		}
					
		public function setTema($tema) {
			$this->tema = $tema;
		}
		
		public function getTema() {
			return $this->tema;
		}
					
		public function setIdentificador($identificador) {
			$this->identificador = $identificador;
		}
		
		public function getIdentificador() {
			return $this->identificador;
		}
					
		public function setCor_primaria($cor_primaria) {
			$this->cor_primaria = $cor_primaria;
		}
		
		public function getCor_primaria() {
			return $this->cor_primaria;
		}
					
		public function setCor_secundaria($cor_secundaria) {
			$this->cor_secundaria = $cor_secundaria;
		}
		
		public function getCor_secundaria() {
			return $this->cor_secundaria;
		}
					
		public function setCor_texto($cor_texto) {
			$this->cor_texto = $cor_texto;
		}
		
		public function getCor_texto() {
			return $this->cor_texto;
		}
					
		public function setFoto($foto) {
			$this->foto = $foto;
		}
		
		public function getFoto() {
			return $this->foto;
		}
					
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
		
		public function getCadastrado() {
			return $this->cadastrado;
		}
					
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
		
		public function getModificado() {
			return $this->modificado;
		}
					
	}
	
?>