<?php

	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mário Sakamoto <mskamot@gmail.com>
	 * @see http://mariosakamoto.com/getz
	 */

	use lib\getz;
	use src\model;	

	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	if (!getActiveSession($_ROOT . $_MODULE))
		echo "<script>goTo(\"/login/1\");</script>";
	else {
		/*
		 * Read
		 */
		if ($method == "stateRead") {	
			$daoFactory->beginTransaction();
			$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = '" . $screen . "'", "", true);
			
			$first[11] = date("Y-m-01");
			$first[10] = date("Y-m-01", strtotime("-1 months", strtotime(date("Y-m-d"))));
			$first[9] = date("Y-m-01", strtotime("-2 months", strtotime(date("Y-m-d"))));
			$first[8] = date("Y-m-01", strtotime("-3 months", strtotime(date("Y-m-d"))));
			$first[7] = date("Y-m-01", strtotime("-4 months", strtotime(date("Y-m-d"))));
			$first[6] = date("Y-m-01", strtotime("-5 months", strtotime(date("Y-m-d"))));
			$first[5] = date("Y-m-01", strtotime("-6 months", strtotime(date("Y-m-d"))));
			$first[4] = date("Y-m-01", strtotime("-7 months", strtotime(date("Y-m-d"))));
			$first[3] = date("Y-m-01", strtotime("-8 months", strtotime(date("Y-m-d"))));
			$first[2] = date("Y-m-01", strtotime("-9 months", strtotime(date("Y-m-d"))));
			$first[1] = date("Y-m-01", strtotime("-10 months", strtotime(date("Y-m-d"))));
			$first[0] = date("Y-m-01", strtotime("-11 months", strtotime(date("Y-m-d"))));
			
			$last[11] = date("Y-m-t", strtotime($first[11]));
			$last[10] = date("Y-m-t", strtotime($first[10]));
			$last[9] = date("Y-m-t", strtotime($first[9]));
			$last[8] = date("Y-m-t", strtotime($first[8]));
			$last[7] = date("Y-m-t", strtotime($first[7]));
			$last[6] = date("Y-m-t", strtotime($first[6]));
			$last[5] = date("Y-m-t", strtotime($first[5]));
			$last[4] = date("Y-m-t", strtotime($first[4]));
			$last[3] = date("Y-m-t", strtotime($first[3]));
			$last[2] = date("Y-m-t", strtotime($first[2]));
			$last[1] = date("Y-m-t", strtotime($first[1]));
			$last[0] = date("Y-m-t", strtotime($first[0]));
			
			/*
			 * Mensais
			 */
			for ($i = 0; $i < sizeof($first); $i++) {
				/*
				 * Medicoes
				 */
				$where = "medicoes.data_hora >= '" . $first[$i] . 
						"' AND medicoes.data_hora <= '" . $last[$i] . "'";	
						
				$medicoesDao = $daoFactory->getMedicoesDao()->read($where, "", true);
				
				$medicoes = 1;
				$temperaturas = 0;
				$pressoes = 0;
				$humidades = 0;
				$solos = 0;
				$alturas = 0;
				
				for ($x = 0; $x < sizeof($medicoesDao); $x++) {
					$medicoes++;
					
					$temperaturas += controllerDouble($medicoesDao[$x]["medicoes.temperatura_ar"]);
					$pressoes += controllerDouble($medicoesDao[$x]["medicoes.pressao_ar"]);
					$humidades += controllerDouble($medicoesDao[$x]["medicoes.humidade_ar"]);
					$solos += controllerDouble($medicoesDao[$x]["medicoes.humidade_solo"]);
					$alturas += controllerDouble($medicoesDao[$x]["medicoes.altura_mar"]);
				}
				
				if ($medicoes > 1)
					$medicoes--;
				
				$temperaturasMedia = modelDouble($temperaturas / $medicoes);
				$pressoesMedia = modelDouble($pressoes / $medicoes);
				$humidadesMedia = modelDouble($humidades / $medicoes);
				$solosMedia = modelDouble($solos / $medicoes);
				$alturasMedia = modelDouble($alturas / $medicoes);
				
				/*
				 * Temperaturas
				 */
				$response[0]["temperaturas"][$i]["temperaturas.subtotal"] = 
						(($i > 0 ? ",'" : "'") . ($temperaturas == 0 ? 0 . "'" : controllerDouble($temperaturasMedia) . "'"));
						
				$response[0]["temperaturas"][$i]["temperaturas.month"] = ($i > 0 ? ",'" : "'") . getMounth($first[$i]) . "'";
				
				/*
				 * Pressoes
				 */
				$response[0]["pressoes"][$i]["pressoes.subtotal"] = 
						(($i > 0 ? ",'" : "'") . ($pressoes == 0 ? 0 . "'" : controllerDouble($pressoesMedia) . "'"));
						
				$response[0]["pressoes"][$i]["pressoes.month"] = ($i > 0 ? ",'" : "'") . getMounth($first[$i]) . "'";
				
				/*
				 * Humidades
				 */
				$response[0]["humidades"][$i]["humidades.subtotal"] = 
						(($i > 0 ? ",'" : "'") . ($humidades == 0 ? 0 . "'" : controllerDouble($humidadesMedia) . "'"));
						
				$response[0]["humidades"][$i]["humidades.month"] = ($i > 0 ? ",'" : "'") . getMounth($first[$i]) . "'";	
				
				/*
				 * Solos
				 */
				$response[0]["solos"][$i]["solos.subtotal"] = 
						(($i > 0 ? ",'" : "'") . ($solos == 0 ? 0 . "'" : controllerDouble($solosMedia) . "'"));
						
				$response[0]["solos"][$i]["solos.month"] = ($i > 0 ? ",'" : "'") . getMounth($first[$i]) . "'";	
				
				/*
				 * Alturas
				 */
				$response[0]["alturas"][$i]["alturas.subtotal"] = 
						(($i > 0 ? ",'" : "'") . ($alturas == 0 ? 0 . "'" : controllerDouble($alturasMedia) . "'"));
						
				$response[0]["alturas"][$i]["alturas.month"] = ($i > 0 ? ",'" : "'") . getMounth($first[$i]) . "'";	
			}
			
			/*
			 * Diarias
			 */				
			$arr = getList($daoFactory,20,"temperatura_ar");
			print_r($arr);
			$horaAtual = 20;
			$horaMinima = $horaAtual - 12;
			
			
			for ($x = 0; $x < sizeof($arr); $x++) {				
				//echo "X: ".$x;
				$temperaturas = $arr[$x];
				
				$response[0]["temperaturas_diarias"][$x]["temperaturas_diarias.subtotal"] = 
					(($x > 0 ? ",'" : "'") . ($temperaturas == 0 ? 0 . "'" : controllerDouble(modelDouble($temperaturas)) . "'"));
			
				$response[0]["temperaturas_diarias"][$x]["temperaturas_diarias.month"] = ($x > 0 ? ",'" : "'") . 
						($horaMinima+$x).":00". "'";	
			}
				
			$arr = getList($daoFactory,20,"pressao_ar");
			//print_r($arr);
			$horaAtual = 20;
			$horaMinima = $horaAtual - 12;
			
			
			for ($x = 0; $x < sizeof($arr); $x++) {				
				echo "X: ".$x;
				$temperaturas = $arr[$x];
				
				$response[0]["pressao_ar"][$x]["pressao_ar.subtotal"] = 
					(($x > 0 ? ",'" : "'") . ($temperaturas == 0 ? 0 . "'" : controllerDouble($temperaturas) . "'"));
			
				$response[0]["pressao_ar"][$x]["pressao_ar.month"] = ($x > 0 ? ",'" : "'") . 
						($horaMinima+$x).":00" . "'";	
			}
				
			$daoFactory->close();

			echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.htm");
			echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/dashboard/dashboardCST.htm");
		}
	}

	function getList($daoFactory,$horaAtual,$column){
	
		$horaMinima = $horaAtual - 12;
	
		$addCount = 0;
		for($h = $horaMinima; $h < $horaAtual; $h++){			
		
			if($h<0){
				$b = $h*-1;
			}else{
				$b = $h;
			}
			
			$where = "HOUR(medicoes.data_hora) =".$b;
			//debug_to_console("hora: ".$where);
			$medicoesDao = $daoFactory->getMedicoesDao()->read($where, "medicoes.id DESC ", false);
			$calc = 0;
			for ($x = 0; $x < sizeof($medicoesDao); $x++) {				
				$calc += $medicoesDao[$x]["medicoes.".$column];				
			}
			//debug_to_console("CALC: ".$calc);
			
			if(sizeof($medicoesDao) > 0){
				$arr[$addCount] = $calc / sizeof($medicoesDao);
			}else{
				$arr[$addCount] = 0;
			}
			$addCount++;
		}		
		
		return $arr;
	}
	
	function debug_to_console( $data ) {
    $output = $data;
    if ( is_array( $output ) )
        $output = implode( ',', $output);

    echo "<script>console.log( 'Debug Objects: " . $output . "' );</script>";
}
?>