<?php

	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mário Sakamoto <mskamot@gmail.com>
	 * @see http://mariosakamoto.com/getz
	 */
	 
	use lib\getz;
	use src\model;
	 
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");

	/*
	 * Login
	 */
	if ($method == "login") {
		$where = "usuarios.email = '" . $form[0] . "' AND " .
				"usuarios.senha = '" . $form[1] . "' AND " .
				"usuarios.status = 1";

		$daoFactory->beginTransaction();
		$usuarios = $daoFactory->getUsuariosDao()->read($where, "", true);
		$daoFactory->close();

		if ($usuarios[0]["usuarios.size"] != 0) {
			$response[0]["message"] = "success";
			
			setActiveSession($_ROOT . $_MODULE);
			setUserSession($_ROOT . $_MODULE, $usuarios);
		} else
			$response[0]["message"] = "error";
			
		echo $darth->json($response);
	} else {
		/*
		 * If Logged
		 */
		if (sizeof($session) > 0)
			echo "<script>goTo(\"/" . $_HOME . "/1\");</script>";
		else
			echo $darth->view("", $_DOCUMENT_ROOT . $_PACKAGE . "/html/login/loginCST.htm");
	}

?>