<?php

	/**
	 * Generated by Getz Framework
	 *
	 * @author Mário Sakamoto <mskamot@gmail.com>
	 * @see http://mariosakamoto.com/getz
	 */
	 
	use lib\getz;
	use src\model;	 

	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	/*
	 * Filters
	 */
	$where = "";
	
	if ($search != "")
		$where = "menus.menu LIKE \"%" . $search . "%\"";	
		
	if ($code != "")
		$where = "menus.id = " . $code;
		
	if ($order != "") {
		$o = explode("<gz>", $order);

		$limit = $o[0] . " " . $o[1] . " LIMIT " . 
				(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;
				
	} else
		$limit = "menus.id DESC LIMIT " . 
				(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;	
	
	/**************************************************
	 * Webpage
	 **************************************************/		
	
	/*
	 * Page
	 */
	if ($method == "page") {
		/*
		 * SEO
		 */
		$darth->setTitle($screen);
		$darth->setDescription("");
		$darth->setKeywords("");
		
		$daoFactory->beginTransaction();
		$response[0]["menus"] = $daoFactory->getMenusDao()->read($where, $limit, true);
		$daoFactory->close();

		echo $darth->view("", $_DOCUMENT_ROOT . $_PACKAGE . "/html/header.htm");
		echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus.htm");
		echo $darth->view("", $_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.htm");
	}
	
	/**************************************************
	 * Webservice
	 **************************************************/	

	/*
	 * Method
	 */
	else if ($method == "method")
		echo "Parameters: " . (isset($_GET["parameters"]) ? $_GET["parameters"] : "");	 
	
	/*
	 * Create
	 *
	else if ($method == "ws-create") {
		$menus = new model\Menus();
		$menus->setMenu(logicNull($form[0]));
		$menus->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
		$menus->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
		
		$daoFactory->beginTransaction();
		$resultDao = $daoFactory->getMenusDao()->create($menus);

		if ($resultDao) {
			$daoFactory->commit();
			$response[0]["message"] = "success";
		} else {							
			$daoFactory->rollback();
			$response[0]["message"] = "error";
		}

		$daoFactory->close();

		echo $darth->json($response);
	}
	*/
	
	/*
	 * Read
	 *
	else if ($method == "ws-read") {
		$daoFactory->beginTransaction();
		$response[0]["menus"] = $daoFactory->getMenusDao()->read($where, $limit, false);
		$daoFactory->close();

		echo $darth->json($response[0]["menus"]);
	}
	*/
	
	/*
	 * Update
	 *
	else if ($method == "ws-update") {	
		$menus = new model\Menus();
		$menus->setId($code);
		$menus->setMenu(logicNull($form[0]));
		$menus->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
		$menus->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
		
		$daoFactory->beginTransaction();
		$resultDao = $daoFactory->getMenusDao()->update($menus);

		if ($resultDao) {
			$daoFactory->commit();
			$response[0]["message"] = "success";
		} else {							
			$daoFactory->rollback();
			$response[0]["message"] = "error";
		}

		$daoFactory->close();

		echo $darth->json($response);
	}
	*/
	
	/* 
	 * Delete
	 *
	else if ($method == "ws-delete") {
		$result = true;
		$lines = explode("<gz>", $code);

		$daoFactory->beginTransaction();

		for ($i = 0; $i < sizeof($lines); $i++) {
			$where = "menus.id = " . $lines[$i];
			
			$resultDao = $daoFactory->getMenusDao()->delete($where);
			$result = !$result ? false : (!$resultDao ? false : true);
		}

		if ($result) {
			$daoFactory->commit();
			$response[0]["message"] = "success";
		} else {							
			$daoFactory->rollback();
			$response[0]["message"] = "error";
		}

		$daoFactory->close();

		echo $darth->json($response);
	} 	
	*/
	
	/**************************************************
	 * System
	 **************************************************/	
	
	else {
		if (!getActiveSession($_ROOT . $_MODULE)) 
			echo "<script>goTo(\"/login/1\");</script>";
		else {
			/*
			 * Create
			 */
			if ($method == "stateCreate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = '" . $screen . "'", "", true);
					$daoFactory->close();

					echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.htm");
					echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCRT.htm");
				}
			}

			/*
			 * Read
			 */
			else if ($method == "stateRead") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = '" . $screen . "'", "", true);
					$response[0]["menus"] = $daoFactory->getMenusDao()->read($where, $limit, true);
					$daoFactory->close();

					echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.htm");
					echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusRD.htm");
				}
			}

			/*
			 * Update
			 */
			else if ($method == "stateUpdate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = '" . $screen . "'", "", true);
					$response[0]["menus"] = $daoFactory->getMenusDao()->read($where, "", true);
					$daoFactory->close();

					echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.htm");
					echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusUPD.htm");
				}
			}

			/*
			 * Called
			 */
			else if ($method == "stateCalled") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					/*
					 * Insert your foreign key here
					 */
					if ($where != "")
						$where .= " AND menus.@_FOREIGN_KEY = " . $base;
					else 
						$where = "menus.@_FOREIGN_KEY = " . $base;
						
					$daoFactory->beginTransaction();
					$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = '" . $screen . "'", "", true);
					$response[0]["menus"] = $daoFactory->getMenusDao()->read($where, $limit, true);
					$daoFactory->close();

					echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.htm");
					echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCLL.htm");
				}
			}

			/*
			 * Screen
			 */
			else if ($method == "screen") {
				if ($base != "") {
					$arrBase = explode("<gz>", $base);
					
					if (sizeof($arrBase) > 1)
						$where = "menus.@_FOREIGN_KEY = " . $arrBase[1];
				}
				
				$limit = "menus.id DESC LIMIT " . (($position * 5) - 5) . ", 5";

				$daoFactory->beginTransaction();
				$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = '" . $screen . "'", "", true);
				$response[0]["menus"] = $daoFactory->getMenusDao()->read($where, $limit, true);
				$daoFactory->close();

				echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusSCR.htm") . 
						"<size>" . $response[0]["menus"][0]["menus.size"] . "<theme>" . 
						$_USER[0]["usuarios"][0]["temas.identificador"];
			}

			/*
			 * Screen handler
			 */
			else if ($method == "screenHandler") {	
				$where = "";

				// Get value from combo
				$cmb = explode("<gz>", $search);

				if ($cmb[1] != "")
					$where = "menus.id = " . $cmb[1];

				$daoFactory->beginTransaction();
				$response[0]["menus"] = $daoFactory->getMenusDao()->comboScr($where);
				$daoFactory->close();

				echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCMB.htm");
			}

			/*
			 * Create
			 */
			else if ($method == "create") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response[0]["message"] = "permission";
					
					echo $darth->json($response);
				} else {
					$menus = new model\Menus();
					$menus->setMenu(logicNull($form[0]));
					$menus->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$menus->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getMenusDao()->create($menus);

					if ($resultDao) {
						$daoFactory->commit();
						$response[0]["message"] = "success";				
					} else {							
						$daoFactory->rollback();
						$response[0]["message"] = "error";
					}

					$daoFactory->close();

					echo $darth->json($response);
				}
			}

			/*
			 * Action update
			 */
			else if ($method == "update") {	
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response[0]["message"] = "permission";
					
					echo $darth->json($response);
				} else {
					$menus = new model\Menus();
					$menus->setId($code);
					$menus->setMenu(logicNull($form[0]));
					$menus->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$menus->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getMenusDao()->update($menus);

					if ($resultDao) {
						$daoFactory->commit();
						$response[0]["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response[0]["message"] = "error";
					}

					$daoFactory->close();

					echo $darth->json($response);
				}
			}
			
			/* 
			 * Action delete
			 */
			else if ($method == "delete") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response[0]["message"] = "permission";
					
					echo $darth->json($response);
				} else {
					$result = true;
					$lines = explode("<gz>", $code);

					$daoFactory->beginTransaction();

					for ($i = 1; $i < sizeof($lines); $i++) {
						$where = "menus.id = " . $lines[$i];
						
						$resultDao = $daoFactory->getMenusDao()->delete($where);
						$result = !$result ? false : (!$resultDao ? false : true);
					}

					if ($result) {
						$daoFactory->commit();
						$response[0]["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response[0]["message"] = "error";
					}

					$daoFactory->close();

					echo $darth->json($response);	
				}
			}
		}
	}

?>