<?php

	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mário Sakamoto <mskamot@gmail.com>
	 * @see http://mariosakamoto.com/getz
	 */

	use lib\getz;
	use src\model;	

	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	if (!getActiveSession($_ROOT . $_MODULE))
		echo "<script>goTo(\"/login/1\");</script>";
	else {
		/*
		 * Update
		 */
		if ($method == "update") {
			/*
			 * Get data
			 */
			$where = "usuarios.id = " . $session[0]["usuarios.id"];
			
			$daoFactory->beginTransaction();
			$data = $daoFactory->getUsuariosDao()->read($where, "", false);
			
			if (logicNull($form[2]) == $data[0]["usuarios.senha"]) {
				$usuarios = new model\Usuarios();
				$usuarios->setId($data[0]["usuarios.id"]);
				$usuarios->setUsuario(logicNull($form[0]));
				$usuarios->setEmail($data[0]["usuarios.email"]);
				$usuarios->setSenha(logicNull($form[3]));
				$usuarios->setFoto($data[0]["usuarios.foto"]);
				$usuarios->setCadastrado(date("Y-m-d H:i:s"));
				$usuarios->setModificado(date("Y-m-d H:i:s"));
				$usuarios->setPerfil($data[0]["usuarios.perfil"]);
				$usuarios->setStatus($data[0]["usuarios.status"]);
				$usuarios->setTema(logicNull($form[1]));
					
				$resultDao = $daoFactory->getUsuariosDao()->update($usuarios);

				if ($resultDao) {
					$daoFactory->commit();
					$response[0]["message"] = "success";
				} else {							
					$daoFactory->rollback();
					$response[0]["message"] = "error";
				}	
			} else
				$response[0]["message"] = "error";

			$daoFactory->close();
			
			echo $darth->json($response);
		}
		
		/*
		 * Read
		 */
		else if ($method == "stateRead") {		
			$where = "usuarios.id = " . $session[0]["usuarios.id"];
			
			$daoFactory->beginTransaction();
			$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = '" . $screen . "'", "", true);
			$response[0]["usuarios"] = $daoFactory->getUsuariosDao()->read($where, "", true);
			$daoFactory->close();
			
			echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.htm");
			echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/minha_conta/minha_contaCST.htm");
		}
	}

?>