<?php

	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mário Sakamoto <mskamot@gmail.com>
	 * @see http://mariosakamoto.com/getz
	 */

	use lib\getz;
	use src\model;	

	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	if (!getActiveSession($_ROOT . $_MODULE))
		echo "<script>goTo(\"/login/1\");</script>";
	else {
		/*
		 * Update
		 */
		if ($method == "update") {
			/*
			 * Get data
			 */
			$where = "usuarios.id = " . $session[0]["usuarios.id"];
			
			$daoFactory->beginTransaction();
			$data = $daoFactory->getUsuariosDao()->read($where, "", false);

			$usuarios = new model\Usuarios();
			$usuarios->setId($data[0]["usuarios.id"]);
			$usuarios->setUsuario($data[0]["usuarios.usuario"]);
			$usuarios->setEmail($data[0]["usuarios.email"]);
			$usuarios->setSenha($data[0]["usuarios.senha"]);
			
			/*
			 * Upload File
			 */
			if (isset($_FILES["upload"])) {
				if ($data[0]["usuarios.foto"] != "") {	
					/*
					 * Unlink
					 */
					unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $data[0]["usuarios.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $data[0]["usuarios.foto"]);
				}
				
				$upload = new getz\Upload($_FILES["upload"], 680);
				$usuarios->setFoto($upload->getName());
			} else 
				$usuarios->setFoto($data[0]["usuarios.foto"]);	

			$usuarios->setCadastrado(date("Y-m-d H:i:s"));
			$usuarios->setModificado(date("Y-m-d H:i:s"));
			$usuarios->setPerfil($data[0]["usuarios.perfil"]);
			$usuarios->setStatus($data[0]["usuarios.status"]);
			$usuarios->setTema($data[0]["usuarios.tema"]);
				
			$resultDao = $daoFactory->getUsuariosDao()->update($usuarios);

			if ($resultDao) {
				$daoFactory->commit();
				$response[0]["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response[0]["message"] = "error";
			}	
			
			$daoFactory->close();
			
			echo $darth->json($response);
		}
		
		/*
		 * Read
		 */
		else if ($method == "stateRead") {		
			$where = "usuarios.id = " . $session[0]["usuarios.id"];
			
			$daoFactory->beginTransaction();
			$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = '" . $screen . "'", "", true);
			$response[0]["usuarios"] = $daoFactory->getUsuariosDao()->read($where, "", true);
			$daoFactory->close();

			echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.htm");
			echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/mudar_foto/mudar_fotoCST.htm");
		}
	}

?>