<?php

	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mário Sakamoto <mskamot@gmail.com>
	 * @see http://mariosakamoto.com/getz
	 */

	use lib\getz;
	use src\model;	

	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	if (!getActiveSession($_ROOT . $_MODULE))
		echo "<script>goTo(\"/login/1\");</script>";
	else {
		/*
		 * Update
		 */
		if ($method == "update") {
			/*
			 * Get data
			 */
			$where = "users.id = " . $session[0]["users.id"];
			
			$daoFactory->beginTransaction();
			$data = $daoFactory->getUsersDao()->read($where, "", false);
			
			if (logicNull($form[2]) == $data[0]["users.password"]) {
				$users = new model\Users();
				$users->setId($data[0]["users.id"]);
				$users->setUser(logicNull($form[0]));
				$users->setEmail($data[0]["users.email"]);
				$users->setPassword(logicNull($form[3]));
				$users->setPhoto($data[0]["users.photo"]);	
				$users->setRegistered(date("Y-m-d H:i:s"));
				$users->setModified(date("Y-m-d H:i:s"));
				$users->setProfile($data[0]["users.profile"]);
				$users->setStatus($data[0]["users.status"]);
				$users->setTheme(logicNull($form[1]));
					
				$resultDao = $daoFactory->getUsersDao()->update($users);

				if ($resultDao) {
					$daoFactory->commit();
					$response[0]["message"] = "success";
				} else {							
					$daoFactory->rollback();
					$response[0]["message"] = "error";
				}	
			} else
				$response[0]["message"] = "error";

			$daoFactory->close();
			
			echo $darth->json($response);
		}
		
		/*
		 * Read
		 */
		else if ($method == "stateRead") {		
			$where = "users.id = " . $session[0]["users.id"];
			
			$daoFactory->beginTransaction();
			$response[0]["titles"] = $daoFactory->getScreensDao()->read("screens.identifier = '" . $screen . "'", "", true);
			$response[0]["users"] = $daoFactory->getUsersDao()->read($where, "", true);
			$daoFactory->close();
			
			echo $darth->view("", $_DOCUMENT_ROOT . $_PACKAGE . "/html/bars/barsCST.htm");
			echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.htm");
			echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/my_account/my_accountCST.htm");
		}
	}

?>