<?php

	/**
	 * Generated by Getz Framework
	 *
	 * @author Mário Sakamoto <mskamot@gmail.com>
	 * @see http://mariosakamoto.com/getz
	 */
	 
	use lib\getz;
	use src\model;	 

	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	/*
	 * Filters
	 */
	$where = "";
	
	if ($search != "")
		$where = "usuarios.usuario LIKE \"%" . $search . "%\"";	
		
	if ($code != "")
		$where = "usuarios.id = " . $code;
		
	if ($order != "") {
		$o = explode("<gz>", $order);

		$limit = $o[0] . " " . $o[1] . " LIMIT " . 
				(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;
				
	} else
		$limit = "usuarios.id DESC LIMIT " . 
				(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;	
	
	/**************************************************
	 * Webpage
	 **************************************************/		
	
	/*
	 * Page
	 */
	if ($method == "page") {
		/*
		 * SEO
		 */
		$darth->setTitle($screen);
		$darth->setDescription("");
		$darth->setKeywords("");
		
		$daoFactory->beginTransaction();
		$response[0]["usuarios"] = $daoFactory->getUsuariosDao()->read($where, $limit, true);
		$daoFactory->close();

		echo $darth->view("", $_DOCUMENT_ROOT . $_PACKAGE . "/html/header.htm");
		echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/usuarios.htm");
		echo $darth->view("", $_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.htm");
	}
	
	/**************************************************
	 * Webservice
	 **************************************************/	

	/*
	 * Method
	 */
	else if ($method == "method")
		echo "Parameters: " . (isset($_GET["parameters"]) ? $_GET["parameters"] : "");	 
	
	/*
	 * Create
	 *
	else if ($method == "ws-create") {
		$usuarios = new model\Usuarios();
		$usuarios->setUsuario(logicNull($form[0]));
		$usuarios->setEmail(logicNull($form[1]));
		$usuarios->setSenha(logicNull($form[2]));
		
		if (isset($_FILES["upload"])) {
			$upload = new getz\Upload($_FILES["upload"], 680);
			$usuarios->setFoto($upload->getName());
		} else 
			$usuarios->setFoto("");
			
		$usuarios->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
		$usuarios->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
		$usuarios->setStatus($form[3]);
		$usuarios->setPerfil($form[4]);
		$usuarios->setTema($form[5]);
		
		$daoFactory->beginTransaction();
		$resultDao = $daoFactory->getUsuariosDao()->create($usuarios);

		if ($resultDao) {
			$daoFactory->commit();
			$response[0]["message"] = "success";
		} else {							
			$daoFactory->rollback();
			$response[0]["message"] = "error";
		}

		$daoFactory->close();

		echo $darth->json($response);
	}
	*/
	
	/*
	 * Read
	 *
	else if ($method == "ws-read") {
		$daoFactory->beginTransaction();
		$response[0]["usuarios"] = $daoFactory->getUsuariosDao()->read($where, $limit, false);
		$daoFactory->close();

		echo $darth->json($response[0]["usuarios"]);
	}
	*/
	
	/*
	 * Update
	 *
	else if ($method == "ws-update") {	
		$usuarios = new model\Usuarios();
		$usuarios->setId($code);
		$usuarios->setUsuario(logicNull($form[0]));
		$usuarios->setEmail(logicNull($form[1]));
		$usuarios->setSenha(logicNull($form[2]));
		
		$where = "usuarios.id = " . $code;
		
		$daoFactory->beginTransaction();
		$usuariosDao = $daoFactory->getUsuariosDao()->read($where, "", false);
		$daoFactory->close();
			
		if (isset($_FILES["upload"])) {
			if ($usuariosDao[0]["usuarios.foto"] != "") {	
				unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $usuariosDao[0]["usuarios.foto"]);
				unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $usuariosDao[0]["usuarios.foto"]);
			}
			
			$upload = new getz\Upload($_FILES["upload"], 680);
			$usuarios->setFoto($upload->getName());
		} else 
			$usuarios->setFoto($usuariosDao[0]["usuarios.foto"]);
			
		$usuarios->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
		$usuarios->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
		$usuarios->setStatus($form[3]);
		$usuarios->setPerfil($form[4]);
		$usuarios->setTema($form[5]);
		
		$daoFactory->beginTransaction();
		$resultDao = $daoFactory->getUsuariosDao()->update($usuarios);

		if ($resultDao) {
			$daoFactory->commit();
			$response[0]["message"] = "success";
		} else {							
			$daoFactory->rollback();
			$response[0]["message"] = "error";
		}

		$daoFactory->close();

		echo $darth->json($response);
	}
	*/
	
	/* 
	 * Delete
	 *
	else if ($method == "ws-delete") {
		$result = true;
		$lines = explode("<gz>", $code);

		$daoFactory->beginTransaction();

		for ($i = 0; $i < sizeof($lines); $i++) {
			$where = "usuarios.id = " . $lines[$i];
			
			$usuariosDao = $daoFactory->getUsuariosDao()->read($where, "", false);
			
			if ($usuariosDao[0]["usuarios.foto"] != "") {	
				unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $usuariosDao[0]["usuarios.foto"]);
				unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $usuariosDao[0]["usuarios.foto"]);
			}
			
			$resultDao = $daoFactory->getUsuariosDao()->delete($where);
			$result = !$result ? false : (!$resultDao ? false : true);
		}

		if ($result) {
			$daoFactory->commit();
			$response[0]["message"] = "success";
		} else {							
			$daoFactory->rollback();
			$response[0]["message"] = "error";
		}

		$daoFactory->close();

		echo $darth->json($response);
	} 	
	*/
	
	/**************************************************
	 * System
	 **************************************************/	
	
	else {
		if (!getActiveSession($_ROOT . $_MODULE)) 
			echo "<script>goTo(\"/login/1\");</script>";
		else {
			/*
			 * Create
			 */
			if ($method == "stateCreate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = '" . $screen . "'", "", true);
					$daoFactory->close();

					echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.htm");
					echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/usuarios/usuariosCRT.htm");
				}
			}

			/*
			 * Read
			 */
			else if ($method == "stateRead") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = '" . $screen . "'", "", true);
					$response[0]["usuarios"] = $daoFactory->getUsuariosDao()->read($where, $limit, true);
					$daoFactory->close();

					echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.htm");
					echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/usuarios/usuariosRD.htm");
				}
			}

			/*
			 * Update
			 */
			else if ($method == "stateUpdate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = '" . $screen . "'", "", true);
					$response[0]["usuarios"] = $daoFactory->getUsuariosDao()->read($where, "", true);
					$daoFactory->close();

					echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.htm");
					echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/usuarios/usuariosUPD.htm");
				}
			}

			/*
			 * Called
			 */
			else if ($method == "stateCalled") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					/*
					 * Insert your foreign key here
					 */
					if ($where != "")
						$where .= " AND usuarios.@_FOREIGN_KEY = " . $base;
					else 
						$where = "usuarios.@_FOREIGN_KEY = " . $base;
						
					$daoFactory->beginTransaction();
					$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = '" . $screen . "'", "", true);
					$response[0]["usuarios"] = $daoFactory->getUsuariosDao()->read($where, $limit, true);
					$daoFactory->close();

					echo $darth->view(getMenu($daoFactory, $_USER, $screen), $_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.htm");
					echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/usuarios/usuariosCLL.htm");
				}
			}

			/*
			 * Screen
			 */
			else if ($method == "screen") {
				if ($base != "") {
					$arrBase = explode("<gz>", $base);
					
					if (sizeof($arrBase) > 1)
						$where = "usuarios.@_FOREIGN_KEY = " . $arrBase[1];
				}
				
				$limit = "usuarios.id DESC LIMIT " . (($position * 5) - 5) . ", 5";

				$daoFactory->beginTransaction();
				$response[0]["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = '" . $screen . "'", "", true);
				$response[0]["usuarios"] = $daoFactory->getUsuariosDao()->read($where, $limit, true);
				$daoFactory->close();

				echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/usuarios/usuariosSCR.htm") . 
						"<size>" . $response[0]["usuarios"][0]["usuarios.size"] . "<theme>" . 
						$_USER[0]["usuarios"][0]["temas.identificador"];
			}

			/*
			 * Screen handler
			 */
			else if ($method == "screenHandler") {	
				$where = "";

				// Get value from combo
				$cmb = explode("<gz>", $search);

				if ($cmb[1] != "")
					$where = "usuarios.id = " . $cmb[1];

				$daoFactory->beginTransaction();
				$response[0]["usuarios"] = $daoFactory->getUsuariosDao()->comboScr($where);
				$daoFactory->close();

				echo $darth->view($response, $_DOCUMENT_ROOT . $_PACKAGE . "/html/usuarios/usuariosCMB.htm");
			}

			/*
			 * Create
			 */
			else if ($method == "create") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response[0]["message"] = "permission";
					
					echo $darth->json($response);
				} else {
					$usuarios = new model\Usuarios();
					$usuarios->setUsuario(logicNull($form[0]));
					$usuarios->setEmail(logicNull($form[1]));
					$usuarios->setSenha(logicNull($form[2]));
					
					/*
					 * Upload File
					 */
					if (isset($_FILES["upload"])) {
						$upload = new getz\Upload($_FILES["upload"], 680);
						$usuarios->setFoto($upload->getName());
					} else 
						$usuarios->setFoto("");
						
					$usuarios->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$usuarios->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$usuarios->setStatus($form[3]);
					$usuarios->setPerfil($form[4]);
					$usuarios->setTema($form[5]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getUsuariosDao()->create($usuarios);

					if ($resultDao) {
						$daoFactory->commit();
						$response[0]["message"] = "success";				
					} else {							
						$daoFactory->rollback();
						$response[0]["message"] = "error";
					}

					$daoFactory->close();

					echo $darth->json($response);
				}
			}

			/*
			 * Action update
			 */
			else if ($method == "update") {	
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response[0]["message"] = "permission";
					
					echo $darth->json($response);
				} else {
					$usuarios = new model\Usuarios();
					$usuarios->setId($code);
					$usuarios->setUsuario(logicNull($form[0]));
					$usuarios->setEmail(logicNull($form[1]));
					$usuarios->setSenha(logicNull($form[2]));
					
					/*
					 * Get object
					 */
					$where = "usuarios.id = " . $code;
					
					$daoFactory->beginTransaction();
					$usuariosDao = $daoFactory->getUsuariosDao()->read($where, "", false);
					$daoFactory->close();
						
					/*
					 * Upload File
					 */
					if (isset($_FILES["upload"])) {
						if ($usuariosDao[0]["usuarios.foto"] != "") {	
							/*
							 * Unlink
							 */
							unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $usuariosDao[0]["usuarios.foto"]);
							unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $usuariosDao[0]["usuarios.foto"]);
						}
						
						$upload = new getz\Upload($_FILES["upload"], 680);
						$usuarios->setFoto($upload->getName());
					} else 
						$usuarios->setFoto($usuariosDao[0]["usuarios.foto"]);
						
					$usuarios->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$usuarios->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$usuarios->setStatus($form[3]);
					$usuarios->setPerfil($form[4]);
					$usuarios->setTema($form[5]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getUsuariosDao()->update($usuarios);

					if ($resultDao) {
						$daoFactory->commit();
						$response[0]["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response[0]["message"] = "error";
					}

					$daoFactory->close();

					echo $darth->json($response);
				}
			}
			
			/* 
			 * Action delete
			 */
			else if ($method == "delete") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response[0]["message"] = "permission";
					
					echo $darth->json($response);
				} else {
					$result = true;
					$lines = explode("<gz>", $code);

					$daoFactory->beginTransaction();

					for ($i = 1; $i < sizeof($lines); $i++) {
						$where = "usuarios.id = " . $lines[$i];
						
						/*
						 * Unlink
						 */
						$usuariosDao = $daoFactory->getUsuariosDao()->read($where, "", false);
						
						if ($usuariosDao[0]["usuarios.foto"] != "") {	
							unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $usuariosDao[0]["usuarios.foto"]);
							unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $usuariosDao[0]["usuarios.foto"]);
						}
						
						$resultDao = $daoFactory->getUsuariosDao()->delete($where);
						$result = !$result ? false : (!$resultDao ? false : true);
					}

					if ($result) {
						$daoFactory->commit();
						$response[0]["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response[0]["message"] = "error";
					}

					$daoFactory->close();

					echo $darth->json($response);	
				}
			}
		}
	}

?>