<?php

	/**
	 * Dao Factory
	 * 
	 * @author Mário Sakamoto <mskamot@gmail.com>
	 * @see http://mariosakamoto.com/getz 
	 */
	 
	namespace src\logic;

	use lib\getz;	
	use src\logic;
	use src\model;	
	
	class DaoFactory extends getz\Dao {
	
		public function __construct($_DAO_FACTORY_IS_OFFICIAL) {
			parent::__construct(new logic\Connection($_DAO_FACTORY_IS_OFFICIAL));
		}

		/*
		 * Generated by Getz
		 */
		
		public function getMedicoesDao() {
			return new model\MedicoesDao($this->getConnection());
		}
		
		public function getMenusDao() {
			return new model\MenusDao($this->getConnection());
		}
		
		public function getPerfil_telasDao() {
			return new model\Perfil_telasDao($this->getConnection());
		}
		
		public function getPerfisDao() {
			return new model\PerfisDao($this->getConnection());
		}
		
		public function getPermissoesDao() {
			return new model\PermissoesDao($this->getConnection());
		}
		
		public function getStatusDao() {
			return new model\StatusDao($this->getConnection());
		}
		
		public function getTelasDao() {
			return new model\TelasDao($this->getConnection());
		}
		
		public function getTemasDao() {
			return new model\TemasDao($this->getConnection());
		}
		
		public function getUsuariosDao() {
			return new model\UsuariosDao($this->getConnection());
		}
		
	}
	
?>